server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: pedido-service
springdoc:
  show-actuator: true
  api-docs:
    áth: book-service/v3/api-docs

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestao
    username: postgres
    password: 123

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/gestao
    user: postgres
    password: 123

  sleuth:
    sampler:
      probability: 1.0